### ISSUE TITLE
Upgrading from sass-rails 4.0.5 to sass-rails 5.0.0 breaks images in jquery-ui-rails gem

### ISSUE THREAD

**Issue by jacob-daniel-waller** [rails/sass-rails#297]
The images found https://github.com/joliss/jquery-ui-rails/blob/master/app/assets/stylesheets/jquery-ui/theme.css.erb here are breaking when upgrading to the latest version of sass-rails.

This is happening when the assets are being compiled and digest is turned on. After the assets are compiled the css is still looking for the non digest images. This is incorrect. Reverting back to sass-rails 4.0.5 fixes this issues and the urls being references are referencing the correct digest URL.

I posted this same issue https://github.com/joliss/jquery-ui-rails/issues/89 here and they said they do not use sass and it should not impact their Gem.

Any help with this would be great. It works fine when I am on 4.0.5. So I am hoping you can point to a change that could impact this.

**Comment by tf** [comment]
This makes it quite dangerous to import any asset pipeline packaged css from an scss file. Soon as the gem maintainer starts including a `require` things fall apart. Or am I missing something?

**Comment by tf** [comment]
This still prevents us from updating our engine to `sass-rails` 5.0 which in turn prevents us from using `sass` > 3.2, which is a shame.

I still don't know how to resolve this conflict:

* I cannot `@import "jquery-ui"` since it does not pick up the `require` directives inside that gem's files.
* I cannot `//= require jquery-ui` in my `my_engine/base.scss` since "I cannot mix import and require"
* I cannot rewrite my `base.scss` to a sprockets based `base.css` since it is supposed to provide mixins to the host application.

All I can do is copy over all requires from `jquery-ui-rails` into my gem and turn them into `@import` statements, which I can then forever keep in sync manually when something changes in the gem.

This is really really broken from my point of view.

**Comment by smargh** [comment]
I finally found this thread after struggling with this issue basically all day. I posted a SO question on my problem in fact: http://stackoverflow.com/q/37715642/2884386

I have to agree with @tf on this point. I cannot figure out a way to work with external assets. Are there any recommended solutions for the scenario where you have to `@import` an external library that is written in pure CSS with Sprockets directives?

**Comment by jasonperrone** [comment]
Guess this was never addressed.

**Comment by jwaiswa7** [comment]
Am stuck with the same issue.. I can't upgrade from sass 3.2, I end up getting an error with image_path

**Comment by jasonperrone** [comment]
Don't know if this will help you, but I found the main issue is having the application.scss file require .css manifest files. A good example is @importing jquery-ui. You can still require individual css files, leaving off the .css extension. So, for example, I can no longer say
@import "jquery-ui";

but I can say:
@import "jquery-ui/core";
@import "jquery-ui/datepicker";
@import "jquery-ui/theme";
@import "jquery-ui/tabs";
@import "jquery-ui/slider";

So, see if your problem is that you're trying to import a .css manifest file and if so, try individually importing the actual css files you need.
