### ISSUE TITLE
require vs. include

### ISSUE THREAD

**Issue by jjb** [rails/sass-rails#306]
The [changelog](https://github.com/rails/sass-rails/blob/master/CHANGELOG.md) says:

> Limit `=require` to .css only files and `@import` to .scss files. Avoid mixing the two.

I looked in the commit history logs and diffs and couldn't find where this change was introduced.

I'd like to know more about it. Why "avoid" -- isn't it a new requirement?

Sorry if I'm missing something obvious. If you can just point me to a commit or some docs I'll figure out the rest myself.

Thanks for a great project!

**Comment by josh** [comment]
You should prefer @import since it actually pulls any mixins into the
current context. =require is sprockets specific and can't do that.

**Comment by jjb** [comment]
Okay, thanks! But in what sense is this now Limited as the changelog says?

Previously did sass rails somehow attempt to also pull `require`ed assets into the current context, but now it doesn't?

**Comment by danajanssen** [comment]
This change silently broke our css that was being included by a bunch of our gem dependencies and took a while to track down the source. We're strictly defining the sass-rails version in our Gemfile for now (and probably should have been doing so from the start) but maybe it's safer to add a depreciation warning instead of just limiting right away? Alternatively a warning to the log for when an asset file is skipped would have been really useful. I'm sure we're not going to be the only people affected by this change!

**Comment by josh** [comment]
> Alternatively a warning to the log for when an asset file is skipped would have been really useful.

I looked into some warnings briefly.  But that would have required using private sass APIs to inspect the contents of those imported files. Which was the reason for dropping support in the first place because we didn't want to depend on sass internals which have changed in the past.

> We're strictly defining the sass-rails version in our Gemfile for now (and probably should have been doing so from the start)

Yeah, 5.0 was a major release, so it had backward incompatible changes.

**Comment by sb8244** [comment]
I had an unexpected issue with this. I was `@include something/in/vendor.css` and it worked great in development. In production, the import was not replaced and was left as a css import. Obviously the vendor files didn't exist in production. Changing it to `//= require something/in/vendor.css` fixed it.

**Comment by tf** [comment]
This is still a complete show stopper preventing me from using `sass-rails` 5.0 and hence `sass` > 3.3 in my engine. Please see [my comment](https://github.com/rails/sass-rails/issues/297#issuecomment-153692870) in this issue
